spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.school.transport: INFO
    root: WARN
